# Generated by Django 5.1.4 on 2024-12-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(blank=True, to="App.tag"),
        ),
    ]
