# Generated by Django 5.1.4 on 2024-12-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_remove_tag_tasks_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="taskCount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(blank=True, default=[], to="App.tag"),
        ),
    ]
