name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      # Start a Selenium Grid container with Chrome (you can modify this depending on your browser requirements)
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g # Increase the size of /dev/shm for Chrome to avoid crashes
        ports:
          - 4444:4444 # Expose the default Selenium WebDriver port

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13 # Specify your Python version

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run Flake8 Linter
      - name: Run Flake8
        run: |
          source venv/bin/activate
          flake8 .

      # Step 5: Run Black Formatter
      - name: Run Black
        run: |
          source venv/bin/activate
          black --check .

      # Step 6: Run Unit Tests
      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          cd TodoList
          coverage run --source='App' --omit='App/tests/integration/*' manage.py test App/tests/unit -v 2
          coverage report
          coverage html -d htmlcov/unit

      # Step 7: Run Integration Tests
      - name: Run Integration Tests
        run: |
          source venv/bin/activate
          cd TodoList 
          coverage run --source='App' --omit='App/tests/unit/*' manage.py test App/tests/integration -v 2
          coverage report

      # Step 8: Run E2E Tests
      - name: Run E2E Tests
        run: |
          source venv/bin/activate
          cd TodoList
          export SELENIUM_URL="http://localhost:4444/wd/hub"  # Selenium URL for the browser session
          python3 manage.py test App/tests/E2E
